---
title: "STA-309-Final"
author: "Chris Reynolds"
date: "`r Sys.Date()`"
output: html_document
---
```{r}
## I loaded my libaries in
library(caret)
library(dplyr)
library(tidyverse)
library(caret)
library(randomForest)
library(ggplot2)
```

```{r}
## I made all my data factors so that it will be able to convert to models 
diabetes_data <- read.csv("diabetes_data.csv")

diabetes_data <- diabetes_data %>% 
  mutate(
    gender = as.factor(gender),
    hypertension = as.factor(hypertension),
    heart_disease = as.factor(heart_disease),
    smoking_history = as.factor(smoking_history),
    diabetes = as.factor(diabetes)
  )

str(diabetes_data)
```

```{r}
## I made the seed the same throughout to keep the same type of results 
set.seed(501)

trainIndex <- createDataPartition(diabetes_data$diabetes, p = 0.8, list = FALSE)
trainData <- diabetes_data[trainIndex, ]
testData <- diabetes_data[-trainIndex, ]
```

```{r}
## In this section I created my models using glm,rpart,rf, and treebag I got help and just quick refeshers on how to use this with Stack Overflow. (2014, November 6). Caret Package method = "treebag" - Stack Overflow. Retrieved December 11, 2024, from https://stackoverflow.com/questions/26789239/caret-package-method-treebag and RDocumentation. (n.d.). glm: Fitting Generalized Linear Models. Retrieved December 11, 2024, from https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/glm


train_control <- trainControl(method = "repeatedcv", number = 5, repeats = 10)

set.seed(501)
logistic_model <- train(
  diabetes ~ ., 
  data = trainData, 
  method = "glm", 
  family = binomial, 
  trControl = train_control
)

set.seed(501)
tree_model <- train(
  diabetes ~ ., 
  data = trainData, 
  method = "rpart", 
  trControl = train_control
)
set.seed(501)
bagging_model <- train(
  diabetes ~ ., 
  data = trainData, 
  method = "treebag", 
  trControl = train_control
)
set.seed(501)
rf_model <- train(
  diabetes ~ ., 
  data = trainData, 
  method = "rf", 
  trControl = train_control
)

set.seed(501)
subset_logistic_model <- train(
  diabetes ~ age + bmi + HbA1c_level, 
  data = trainData, 
  method = "glm", 
  family = binomial, 
  trControl = train_control
)
```

```{r}
## Here I creeated my first plot showing the most important variables as we can see it is HbA1c_level
rf_importance <- varImp(rf_model)
plot(rf_importance, main = "Variable Importance - Random Forest")
```

```{r}
## Here is my model comparision shows how all of the models turend out it seems that random forest model turned out to bes the best
model_list <- list(Logistic = logistic_model, Tree = tree_model, Bagging = bagging_model, RandomForest = rf_model)
results <- resamples(model_list)
summary(results)


bwplot(results, main = "Model Comparison")
```

```{r}
rf_predictions <- predict(rf_model, newdata = testData)
confusionMatrix(rf_predictions, testData$diabetes) 
## Here I created a confusion matrix showing all the statistical calculations I got help from DigitalOcean. (2022, August 3). Confusion Matrix in R | A Complete Guide. Retrieved December 11, 2024, from https://www.digitalocean.com/community/tutorials/confusion-matrix-in-r
```

```{r}
## Here I made a bar chart showing what rf importance is it is the same with HbA1c_level being the most important
rf_importance_plot <- ggplot(rf_importance$importance, aes(x = reorder(rownames(rf_importance$importance), Overall), y = Overall)) +
  geom_bar(stat = "identity", fill = "steelblue") +
  coord_flip() +
  labs(title = "Key Predictors of Diabetes", x = "Variables", y = "Importance") +
  theme_minimal()
print(rf_importance_plot)
```

```{r}
## Next I used a scatter plot to show HbA1c_levels are shown between diabetes
diabetes_scatter <- ggplot(diabetes_data, aes(x = HbA1c_level, y = as.numeric(as.character(diabetes)))) +
  geom_point(alpha = 0.5, color = "darkgreen") +
  geom_smooth(method = "loess", color = "red") +
  labs(title = "HbA1c Level vs. Diabetes", x = "HbA1c Level", y = "Diabetes (0 = No, 1 = Yes)") +
  theme_minimal()
print(diabetes_scatter)
```

```{r}
## Then I showed a box plot to show the correlation of BMI that means body mass index and diabetes. 
bmi_boxplot <- ggplot(diabetes_data, aes(x = diabetes, y = bmi, fill = diabetes)) +
  geom_boxplot() +
  labs(title = "BMI Distribution by Diabetes Status", x = "Diabetes (0 = No, 1 = Yes)", y = "BMI") +
  theme_minimal()
print(bmi_boxplot)
```

```{r}
png("variable_importance.png")
print(rf_importance_plot)
dev.off()
```

```{r}
png("hba1c_scatter.png")
print(diabetes_scatter)
dev.off()
```

```{r}
png("bmi_boxplot.png")
print(bmi_boxplot)
dev.off()
```


